name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/action.js'
      - 'action.yml'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: .dist/*
          commit-msg: 'feat(dist): update resources'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-removing: true
